name: Run Native TS Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v23.x
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start TypeScript Server
        run: |
          node server.ts &
          sleep 5
          curl --fail http://localhost:3000/hello || (echo "Server did not start" && exit 1)

      - name: Expose Port 3000 with ngrok
        run: |
          ngrok http 3000 > /dev/null &
          sleep 5
          curl --silent --fail http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
